<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJjFUSen\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJjFUSen/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJjFUSen.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJjFUSen\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJjFUSen\App_KernelProdContainer([
    'container.build_hash' => 'JjFUSen',
    'container.build_id' => '6970db81',
    'container.build_time' => 1700672428,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJjFUSen');
