<?php

namespace ContainerJjFUSen;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_ValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'api_platform.validator' shared service.
     *
     * @return \ApiPlatform\Symfony\Validator\Validator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['api_platform.validator'] = new \ApiPlatform\Symfony\Validator\Validator(($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['api_platform.graphql.resolver_locator'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], [])));
    }
}
