<?php

namespace ContainerJjFUSen;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_UploadTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'api_platform.graphql.upload_type' shared service.
     *
     * @return \ApiPlatform\GraphQl\Type\Definition\UploadType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['api_platform.graphql.upload_type'] = new \ApiPlatform\GraphQl\Type\Definition\UploadType();
    }
}
