<?php

namespace ContainerJjFUSen;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_Action_EntrypointService extends App_KernelProdContainer
{
    /*
     * Gets the public 'api_platform.graphql.action.entrypoint' shared service.
     *
     * @return \ApiPlatform\GraphQl\Action\EntrypointAction
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['api_platform.graphql.action.entrypoint'] = new \ApiPlatform\GraphQl\Action\EntrypointAction(($container->privates['api_platform.graphql.schema_builder'] ?? $container->load('getApiPlatform_Graphql_SchemaBuilderService')), new \ApiPlatform\GraphQl\Executor(true), ($container->services['api_platform.graphql.action.graphiql'] ?? $container->load('getApiPlatform_Graphql_Action_GraphiqlService')), ($container->services['api_platform.graphql.action.graphql_playground'] ?? $container->load('getApiPlatform_Graphql_Action_GraphqlPlaygroundService')), ($container->privates['serializer'] ?? self::getSerializerService($container)), new \ApiPlatform\GraphQl\Error\ErrorHandler(), false, true, true, 'graphiql');
    }
}
