<?php

namespace ContainerJjFUSen;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEstablishmentRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EstablishmentRepository' shared autowired service.
     *
     * @return \App\Repository\EstablishmentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EstablishmentRepository'] = new \App\Repository\EstablishmentRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
