<?php

namespace ContainerJjFUSen;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PrestationRepository' shared autowired service.
     *
     * @return \App\Repository\PrestationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PrestationRepository'] = new \App\Repository\PrestationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
