<?php

namespace ContainerJjFUSen;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSlotRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SlotRepository' shared autowired service.
     *
     * @return \App\Repository\SlotRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SlotRepository'] = new \App\Repository\SlotRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
