<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ21AWRy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ21AWRy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ21AWRy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ21AWRy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ21AWRy\App_KernelDevDebugContainer([
    'container.build_hash' => 'J21AWRy',
    'container.build_id' => '4fe4b09e',
    'container.build_time' => 1706804833,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ21AWRy');
