<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bookings' => [parent::class, 'bookings', null],
        "\0".parent::class."\0".'confirmPassword' => [parent::class, 'confirmPassword', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'establishment' => [parent::class, 'establishment', null],
        "\0".parent::class."\0".'feedbacks' => [parent::class, 'feedbacks', null],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null],
        "\0".parent::class."\0".'managedEstablishments' => [parent::class, 'managedEstablishments', null],
        "\0".parent::class."\0".'media' => [parent::class, 'media', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'prestataires' => [parent::class, 'prestataires', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        'bookings' => [parent::class, 'bookings', null],
        'confirmPassword' => [parent::class, 'confirmPassword', null],
        'email' => [parent::class, 'email', null],
        'establishment' => [parent::class, 'establishment', null],
        'feedbacks' => [parent::class, 'feedbacks', null],
        'firstname' => [parent::class, 'firstname', null],
        'id' => [parent::class, 'id', null],
        'image' => [parent::class, 'image', null],
        'lastname' => [parent::class, 'lastname', null],
        'managedEstablishments' => [parent::class, 'managedEstablishments', null],
        'media' => [parent::class, 'media', null],
        'password' => [parent::class, 'password', null],
        'prestataires' => [parent::class, 'prestataires', null],
        'roles' => [parent::class, 'roles', null],
        'status' => [parent::class, 'status', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
