<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Booking extends \App\Entity\Booking implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bookedBy' => [parent::class, 'bookedBy', null],
        "\0".parent::class."\0".'bookingDate' => [parent::class, 'bookingDate', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'prestation' => [parent::class, 'prestation', null],
        "\0".parent::class."\0".'slot' => [parent::class, 'slot', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        'bookedBy' => [parent::class, 'bookedBy', null],
        'bookingDate' => [parent::class, 'bookingDate', null],
        'id' => [parent::class, 'id', null],
        'prestation' => [parent::class, 'prestation', null],
        'slot' => [parent::class, 'slot', null],
        'status' => [parent::class, 'status', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
