<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Feedback extends \App\Entity\Feedback implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'comment' => [parent::class, 'comment', null],
        "\0".parent::class."\0".'feedbackDate' => [parent::class, 'feedbackDate', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'issuedBy' => [parent::class, 'issuedBy', null],
        "\0".parent::class."\0".'prestation' => [parent::class, 'prestation', null],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null],
        'comment' => [parent::class, 'comment', null],
        'feedbackDate' => [parent::class, 'feedbackDate', null],
        'id' => [parent::class, 'id', null],
        'issuedBy' => [parent::class, 'issuedBy', null],
        'prestation' => [parent::class, 'prestation', null],
        'rating' => [parent::class, 'rating', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
