<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Prestation extends \App\Entity\Prestation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bookings' => [parent::class, 'bookings', null],
        "\0".parent::class."\0".'category' => [parent::class, 'category', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'duration' => [parent::class, 'duration', null],
        "\0".parent::class."\0".'establishment' => [parent::class, 'establishment', null],
        "\0".parent::class."\0".'feedback' => [parent::class, 'feedback', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null],
        "\0".parent::class."\0".'slots' => [parent::class, 'slots', null],
        'bookings' => [parent::class, 'bookings', null],
        'category' => [parent::class, 'category', null],
        'description' => [parent::class, 'description', null],
        'duration' => [parent::class, 'duration', null],
        'establishment' => [parent::class, 'establishment', null],
        'feedback' => [parent::class, 'feedback', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'price' => [parent::class, 'price', null],
        'slots' => [parent::class, 'slots', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
