<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zx3oYFBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zx3oYFB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zx3oYFB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'uploaderService' => ['privates', 'App\\Services\\UploaderService', 'getUploaderServiceService', true],
        ], [
            'manager' => '?',
            'uploaderService' => 'App\\Services\\UploaderService',
        ]);
    }
}
