<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PSwBGfEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PSwBGfE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PSwBGfE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'establishmentRepository' => ['privates', 'App\\Repository\\EstablishmentRepository', 'getEstablishmentRepositoryService', true],
            'prestataire' => ['privates', '.errored..service_locator.PSwBGfE.App\\Entity\\Prestataire', NULL, 'Cannot autowire service ".service_locator.PSwBGfE": it needs an instance of "App\\Entity\\Prestataire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'establishmentRepository' => 'App\\Repository\\EstablishmentRepository',
            'prestataire' => 'App\\Entity\\Prestataire',
        ]);
    }
}
