<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Graphql_Action_GraphiqlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'api_platform.graphql.action.graphiql' shared service.
     *
     * @return \ApiPlatform\GraphQl\Action\GraphiQlAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/GraphQl/Action/GraphiQlAction.php';

        return $container->services['api_platform.graphql.action.graphiql'] = new \ApiPlatform\GraphQl\Action\GraphiQlAction(($container->privates['twig'] ?? self::getTwigService($container)), ($container->privates['api_platform.router'] ?? self::getApiPlatform_RouterService($container)), true, 'Hello API Platform', NULL);
    }
}
