<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssignManagerToEstablishmentStateProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\AssignManagerToEstablishmentStateProcessor' shared autowired service.
     *
     * @return \App\State\AssignManagerToEstablishmentStateProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/AssignManagerToEstablishmentStateProcessor.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\State\\AssignManagerToEstablishmentStateProcessor'])) {
            return $container->privates['App\\State\\AssignManagerToEstablishmentStateProcessor'];
        }

        return $container->privates['App\\State\\AssignManagerToEstablishmentStateProcessor'] = new \App\State\AssignManagerToEstablishmentStateProcessor($a, ($container->privates['App\\Repository\\EstablishmentRepository'] ?? $container->load('getEstablishmentRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
