<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_StateProcessor_LocatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.state_processor.locator' shared service.
     *
     * @return \ApiPlatform\State\CallableProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/CallableProcessor.php';

        return $container->privates['api_platform.state_processor.locator'] = new \ApiPlatform\State\CallableProcessor(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor' => ['privates', 'api_platform.doctrine.orm.state.persist_processor', 'getApiPlatform_Doctrine_Orm_State_PersistProcessorService', true],
            'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor' => ['privates', 'api_platform.doctrine.orm.state.remove_processor', 'getApiPlatform_Doctrine_Orm_State_RemoveProcessorService', true],
            'App\\State\\ApprovePrestataireProcessor' => ['privates', 'App\\State\\ApprovePrestataireProcessor', 'getApprovePrestataireProcessorService', true],
            'App\\State\\AssignManagerToEstablishmentStateProcessor' => ['privates', 'App\\State\\AssignManagerToEstablishmentStateProcessor', 'getAssignManagerToEstablishmentStateProcessorService', true],
            'App\\State\\CreateEstablishmentProcessor' => ['privates', 'App\\State\\CreateEstablishmentProcessor', 'getCreateEstablishmentProcessorService', true],
            'App\\State\\RegisterEmployeeProcessor' => ['privates', 'App\\State\\RegisterEmployeeProcessor', 'getRegisterEmployeeProcessorService', true],
            'App\\State\\RegisterPrestataireProcessor' => ['privates', 'App\\State\\RegisterPrestataireProcessor', 'getRegisterPrestataireProcessorService', true],
            'App\\State\\RejectPrestataireProcessor' => ['privates', 'App\\State\\RejectPrestataireProcessor', 'getRejectPrestataireProcessorService', true],
            'App\\State\\UserPasswordHasher' => ['privates', 'App\\State\\UserPasswordHasher', 'getUserPasswordHasherService', true],
            'api_platform.doctrine.orm.state.persist_processor' => ['privates', 'api_platform.doctrine.orm.state.persist_processor', 'getApiPlatform_Doctrine_Orm_State_PersistProcessorService', true],
            'api_platform.doctrine.orm.state.remove_processor' => ['privates', 'api_platform.doctrine.orm.state.remove_processor', 'getApiPlatform_Doctrine_Orm_State_RemoveProcessorService', true],
            'api_platform.swagger_ui.processor' => ['privates', 'api_platform.swagger_ui.processor', 'getApiPlatform_SwaggerUi_ProcessorService', true],
        ], [
            'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor' => 'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor',
            'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor' => 'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor',
            'App\\State\\ApprovePrestataireProcessor' => 'App\\State\\ApprovePrestataireProcessor',
            'App\\State\\AssignManagerToEstablishmentStateProcessor' => 'App\\State\\AssignManagerToEstablishmentStateProcessor',
            'App\\State\\CreateEstablishmentProcessor' => 'App\\State\\CreateEstablishmentProcessor',
            'App\\State\\RegisterEmployeeProcessor' => 'App\\State\\RegisterEmployeeProcessor',
            'App\\State\\RegisterPrestataireProcessor' => 'App\\State\\RegisterPrestataireProcessor',
            'App\\State\\RejectPrestataireProcessor' => 'App\\State\\RejectPrestataireProcessor',
            'App\\State\\UserPasswordHasher' => 'App\\State\\UserPasswordHasher',
            'api_platform.doctrine.orm.state.persist_processor' => 'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor',
            'api_platform.doctrine.orm.state.remove_processor' => 'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor',
            'api_platform.swagger_ui.processor' => 'ApiPlatform\\Symfony\\Bundle\\SwaggerUi\\SwaggerUiProcessor',
        ]));
    }
}
