<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateEstablishmentProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\CreateEstablishmentProcessor' shared autowired service.
     *
     * @return \App\State\CreateEstablishmentProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/CreateEstablishmentProcessor.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\State\\CreateEstablishmentProcessor'])) {
            return $container->privates['App\\State\\CreateEstablishmentProcessor'];
        }

        return $container->privates['App\\State\\CreateEstablishmentProcessor'] = new \App\State\CreateEstablishmentProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), $a);
    }
}
