<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetEstablishmentStateProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\GetEstablishmentStateProvider' shared autowired service.
     *
     * @return \App\State\GetEstablishmentStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/State/GetEstablishmentStateProvider.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\State\\GetEstablishmentStateProvider'])) {
            return $container->privates['App\\State\\GetEstablishmentStateProvider'];
        }

        return $container->privates['App\\State\\GetEstablishmentStateProvider'] = new \App\State\GetEstablishmentStateProvider(($container->privates['App\\Repository\\EstablishmentRepository'] ?? $container->load('getEstablishmentRepositoryService')), $a);
    }
}
