<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetEmployeesStateProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\GetEmployeesStateProvider' shared autowired service.
     *
     * @return \App\State\GetEmployeesStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/State/GetEmployeesStateProvider.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\State\\GetEmployeesStateProvider'])) {
            return $container->privates['App\\State\\GetEmployeesStateProvider'];
        }

        return $container->privates['App\\State\\GetEmployeesStateProvider'] = new \App\State\GetEmployeesStateProvider($a, ($container->privates['App\\Repository\\PrestataireRepository'] ?? $container->load('getPrestataireRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
