<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetPrestatairesForUserStateProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\GetPrestatairesForUserStateProvider' shared autowired service.
     *
     * @return \App\State\GetPrestatairesForUserStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/State/GetPrestatairesForUserStateProvider.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\State\\GetPrestatairesForUserStateProvider'])) {
            return $container->privates['App\\State\\GetPrestatairesForUserStateProvider'];
        }

        return $container->privates['App\\State\\GetPrestatairesForUserStateProvider'] = new \App\State\GetPrestatairesForUserStateProvider($a, ($container->privates['App\\Repository\\PrestataireRepository'] ?? $container->load('getPrestataireRepositoryService')));
    }
}
