<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailer_TransportFactory_SendinblueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mailer.transport_factory.sendinblue' shared service.
     *
     * @return \Symfony\Component\Mailer\Bridge\Sendinblue\Transport\SendinblueTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/AbstractTransportFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/sendinblue-mailer/Transport/SendinblueTransportFactory.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['mailer.transport_factory.sendinblue'])) {
            return $container->privates['mailer.transport_factory.sendinblue'];
        }

        return $container->privates['mailer.transport_factory.sendinblue'] = new \Symfony\Component\Mailer\Bridge\Sendinblue\Transport\SendinblueTransportFactory($a, ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['monolog.logger.mailer'] ?? $container->load('getMonolog_Logger_MailerService')));
    }
}
