<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestataireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PSwBGfE.App\Entity\Prestataire' shared service.
     *
     * @return \App\Entity\Prestataire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.PSwBGfE": it needs an instance of "App\\Entity\\Prestataire" but this type has been excluded in "config/services.yaml".');
    }
}
