<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterEmployeeProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\RegisterEmployeeProcessor' shared autowired service.
     *
     * @return \App\State\RegisterEmployeeProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/RegisterEmployeeProcessor.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\State\\RegisterEmployeeProcessor'])) {
            return $container->privates['App\\State\\RegisterEmployeeProcessor'];
        }

        return $container->privates['App\\State\\RegisterEmployeeProcessor'] = new \App\State\RegisterEmployeeProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), $a, ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
