<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterPrestataireProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\RegisterPrestataireProcessor' shared autowired service.
     *
     * @return \App\State\RegisterPrestataireProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/RegisterPrestataireProcessor.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\State\\RegisterPrestataireProcessor'])) {
            return $container->privates['App\\State\\RegisterPrestataireProcessor'];
        }
        $b = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\State\\RegisterPrestataireProcessor'])) {
            return $container->privates['App\\State\\RegisterPrestataireProcessor'];
        }

        return $container->privates['App\\State\\RegisterPrestataireProcessor'] = new \App\State\RegisterPrestataireProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), $a, $b);
    }
}
