<?php

namespace ContainerPKhKACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRejectPrestataireProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\RejectPrestataireProcessor' shared autowired service.
     *
     * @return \App\State\RejectPrestataireProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/RejectPrestataireProcessor.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\State\\RejectPrestataireProcessor'])) {
            return $container->privates['App\\State\\RejectPrestataireProcessor'];
        }
        $b = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\State\\RejectPrestataireProcessor'])) {
            return $container->privates['App\\State\\RejectPrestataireProcessor'];
        }

        return $container->privates['App\\State\\RejectPrestataireProcessor'] = new \App\State\RejectPrestataireProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), $a, $b);
    }
}
